# Generated by Django 5.2.7 on 2025-11-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={'managed': False},
        ),
    ]
